version: "2"

services:
  n3uron:
    image: n3uronhub/n3uron:v1.21.12
    ports:
      - 80:8003 # HTTP WebUI for balena's Public Device URL feature
      - 8003:8003 # HTTP WebUI
      - 8443:8443 # HTTPS WebUI
      - 8004:8004 # HTTP WebVision
      - 8444:8444 # HTTPS WebVision
      - 3001:3001 # Inbound Links
    environment:
      - HOSTNAME=balena-historian
    volumes:
      - config:/opt/n3uron/config
      - data:/opt/n3uron/data
      - licenses:/opt/n3uron/licenses
      - log:/opt/n3uron/log
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    restart: always

  mongo:
    image: mongo:8
    command: --wiredTigerCollectionBlockCompressor zstd
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  config:
  data:
  licenses:
  log:
  mongo_data:
