version: '2'

services:
  n3uron:
    image: n3uronhub/n3uron:v1.21.4
    ports:
      - 80:8003   # HTTP WebUI
      - 443:8443  # HTTPS WebUI
      - 3001:3001 # Inbound Links
    volumes:
      - n3_config:/opt/n3uron/config      # Persist configuration
      - n3_data:/opt/n3uron/data          # Persist data
      - n3_licenses:/opt/n3uron/licenses  # Persist N3uron licenses
      - n3_log:/opt/n3uron/log            # Persist logs
    restart: always

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  n3_config:
  n3_data:
  n3_licenses:
  n3_log:
  mongo_data:
